import type { Metadata } from "next";
import "./globals.css";
import Header from "@components/header/Header";
import Footer from "@components/Footer";


export const metadata: Metadata = {
  title: "DummyCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
       
     
     
     <Header/>
    {children}

   
    <Footer />
       
   </body>
    </html>
  );
}
